### ISSUE TITLE
How i can use this in Xamarin.Android?

### ISSUE THREAD

**Issue by CDrosos** [UdaraAlwis/XFColorPickerControl#1]
Hello,
great work in this plugin, im wondering how i can use it in my Xamarin.Android project, can you assist me on that?

**Comment by UdaraAlwis** [comment]
Thank you for the feedback. This library uses SkiaSharp for Xamarin.Forms in the core. If you could set up SkiaSharp in your Xamarin.Android project, then you can use the same implementation there as well. Simply copy and paste of the SkiaSharp related logic should do the trick I suppose! ;) 
But as of now this library won't be supporting Xamarin.Android :) 
Cheers!
