### ISSUE TITLE
[Feature] Integrate a Rainbow Colour Spectrum

### ISSUE THREAD

**Issue by bricefriha** [UdaraAlwis/XFColorPickerControl#5]
Hello!
This could be cool to have a colour spectrum as @UdaraAlwis showed in https://theconfuzedsourcecode.wordpress.com/2020/02/26/i-built-an-interactive-color-picker-control-for-xamarin-forms/

If you don't have the time to do it I can maybe work on it 😉

**Comment by UdaraAlwis** [comment]
Hello, I'm not sure if I understand your request. Could you explain further?
That blog post link you posted is about this library itself, XFColorPickerControl and it already has the color spectrum feature shown in there.

**Comment by bricefriha** [comment]
Thanks for your reply! 😀
If a colour spectrum is already implemented, how can I use it? because I didn't find it in the doc

**Comment by UdaraAlwis** [comment]
It's well explained in the github docs itself: https://github.com/UdaraAlwis/XFColorPickerControl/blob/master/README.md

Or you could refer to the other blog post where I exaplain how each feature is implemented in code and how to use them: 
https://theconfuzedsourcecode.wordpress.com/2020/03/17/publishing-the-nuget-of-my-color-picker-control-for-xamarin-forms/
Each feature has a "How to use?" section where you can read about how to use them.

Good luck!
Cheers! :)
